name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master  # Le workflow s'exécute sur un push vers la branche 'master'
  pull_request:
    types: [opened, synchronize, reopened, closed]  # Le workflow s'exécute lors de l'ouverture, la synchronisation, la réouverture ou la fermeture d'un pull request
    branches:
      - master  # Concernant les pull requests vers la branche 'master'

jobs:
  # Job de déploiement de l'application
  build_and_deploy_job:
    # Ce job est exécuté lors de push ou lorsqu'un pull request est ouvert/synchronisé/réouvert (mais pas fermé)
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest  # Exécution sur un runner Ubuntu
    name: Build and Deploy Job  # Nom du job
    steps:
      - uses: actions/checkout@v3  # Action pour récupérer le code source
        with:
          submodules: true  # Récupération des sous-modules du dépôt
          lfs: false  # Ignorer les fichiers LFS (Large File Storage)
      - name: Build And Deploy  # Étape de déploiement de l'application
        id: builddeploy  # Identifiant de cette étape
        uses: Azure/static-web-apps-deploy@v1  # Utilisation de l'action Azure pour déployer l'application
        with:
          # Le token Azure pour l'authentification (stocké dans les secrets du dépôt)
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_BAY_038D85E03 }}
          # Le token GitHub pour les interactions liées aux PR (ex. commentaires sur PR)
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"  # L'action à effectuer : ici un "upload" pour déployer l'application


          # Répertoire des API (si présentes)
          api_location: "."  # Le chemin relatif vers les API (facultatif, ici un répertoire './api')

          # Répertoire des fichiers construits (facultatif)
          output_location: "."  # Le répertoire des fichiers construits (ici la racine)

  # Job pour fermer un pull request
  close_pull_request_job:
    # Ce job s'exécute uniquement lorsqu'un pull request est fermé
    if: github.event_name == 'pull_req uest' && github.event.action == 'closed'
    runs-on: ubuntu-latest  # Exécution sur un runner Ubuntu
    name: Close Pull Request Job  # Nom du job
    steps:
      - name: Close Pull Request  # Étape pour fermer le pull request dans Azure
        id: closepullrequest  # Identifiant de l'étape
        uses: Azure/static-web-apps-deploy@v1  # Utilisation de l'action Azure pour fermer le PR
        with:
          # Le token Azure pour l'authentification
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_BAY_038D85E03 }}
          action: "close"  # Action à effectuer : ici fermer le déploiement associé au PR fermé
