name: Build and Deploy to Azure

on:
  push:
    branches:
      - main  # Déclenche le workflow sur un push sur la branche principale
  pull_request:
    branches:
      - main  # Déclenche aussi sur une PR vers la branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Étape 1: Construire l'image Docker
    - name: Build Docker image
      run: |
        docker build -t my-app .

    # Étape 2: Connecter à Azure via votre compte utilisateur (pas de Service Principal)
    - name: Set up Azure CLI
      uses: azure/setup-azure-cli@v1

    - name: Login to Azure
      run: |
        az login --use-device-code  # Utilisation du code de dispositif pour la connexion manuelle
    
    # Étape 3: Pousser l'image Docker vers Azure Container Registry (ACR)
    - name: Push Docker image to Azure Container Registry (ACR)
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}
        docker tag my-app ${{ secrets.ACR_NAME }}.azurecr.io/my-app:latest
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/my-app:latest

    # Étape 4: Initialiser Terraform et appliquer les configurations
    - name: Initialize Terraform
      run: |
        terraform init
        terraform plan -out=tfplan
        terraform apply tfplan

    - name: Cleanup
      run: |
        docker system prune -af
